### ISSUE TITLE
The songs that are picked aren't "random".

### ISSUE THREAD

**Issue by CoolingBacon79** [eightants/whisperify#49]
My friend and I tried and loved this website instantly. However, we quickly noticed that the randomness was a bit off. We wanted to compete by selecting our shared playlist, where we have over 2000 songs. When we made this playlist, we copy-pasted all our playlists into one big playlist, starting with me and then him. The problem with this was that Whisperify only picked songs that I had added. When we restarted the game, it only picked songs that he had added. We drew the conclusion that it selects songs that are located after each other in the playlist, and just randomizes that interval each time. My question is; would it be possible to modify the randomizer to select songs _completely_ random, instead of songs that happen to be next to each other in the playlist?

**Comment by eightants** [comment]
Hi. that's a fair suggestion. Since getting the songs are expensive resource-wise, the app takes an interval of songs in a playlist and randomizes the interval each time. I'll start working on making the randomizer completely random.

**Comment by CoolingBacon79** [comment]
Thanks! Looking forward to trying it out!

**Comment by eightants** [comment]
Fixed with #50
