### ISSUE TITLE
Prettier is not being executed in npm run lint on windows

### ISSUE THREAD

**Issue by CapOfCave** [eightants/whisperify#53]
When trying to run `npm run lint`, an error is thrown: 

```sh
[error] No files matching the pattern were found: "'src/**/*.{ts,tsx,scss}'".
```

Looks like prettier doesn't like single quotes (at least in powershell). Changed it to (escaped) double quotes and everything worked as expected.

```diff
-     "lint": "prettier --check --write 'src/**/*.{ts,tsx,scss}' && npm run lint:es",
+     "lint": "prettier --check --write \"src/**/*.{ts,tsx,scss}\" && npm run lint:es",
```

Unfortunately, this also means that I now have 100 formatting changes on top of my existing ones, but I think I can handle it :D

I can't tell whether prettier used an incorrect style guide on my machine, or whether it has never been executed before. Could you look into that?

**Comment by CapOfCave** [comment]
The first part seems to be a me-problem (or rather a powershell problem) as it's running as expected in different shells.

So only the last part applies: 

> [Why are there so many lint errors?]
>
> I can't tell whether prettier used an incorrect style guide on my machine, or whether it has not been executed in a while. Could you look into that?

**Comment by eightants** [comment]
This should be fixed now.
